/*
 * Sony's per-title configuration overrides, by the disc's serial - what pcsx-ab's config_change()
 * (frontend/menu.c in the 2017 fork) applied over pcsx.cfg at every start for 131 titles, keyed there by
 * the ISO's file name (which on the console was the serial; on a USB stick it was garbage). The table
 * (ab_hacks_table.h, generated by tools/gen_sony_hacks.py from the reference patch) keeps the overrides
 * that have an equivalent in upstream's core: SPU interpolation, the SPU thread, interlace, the region.
 * Sony's other 300-odd per-title sites patched a 2017 core's CD/SPU timing and its P.E.Op.S. GPU and
 * are not ported (CLAUDE.md, "Per-title hacks"); upstream keeps its own per-serial fixes in
 * libpcsxcore/database.c.
 *
 * Off unless the emulator is started with -sonyhacks: a lever for the compatibility pass, not a default.
 *
 * (C) AutoBleem team, 2026 - GPL v2 or later, as the frontend.
 */
#ifndef AB_HACKS_H
#define AB_HACKS_H

/* after a game's config is loaded (ab_config_loaded with is_game): the overrides for CdromId, if
 * -sonyhacks was given; one log line per override applied */
void ab_hacks_apply(void);

#endif
