# Generate frontend/ab/ab_hacks_table.h - Sony's per-title configuration overrides, keyed by serial - from
# the reference patch (docs/reference/pcsx-ab-delta-2017.patch): title.h's serial table and the
# isTitleName() groups of config_change() in frontend/menu.c. Only the overrides with an equivalent in
# upstream's core are kept; the peops-only flags (isToShinDen, regions, dither, iTrimJaggyFrame, the
# plugin swap) and Sony's SPU iTempo are listed in the header comment instead.
#
#   tools/gen_sony_hacks.py            (run from anywhere; rewrites frontend/ab/ab_hacks_table.h)
import os, re, collections

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
patch = open(os.path.join(root, 'docs', 'reference', 'pcsx-ab-delta-2017.patch'), encoding='utf-8', errors='replace').read()

# 1. serial -> TITLE enum
m = re.search(r'static struct INCLUDE_TITLE stTitleList\[\] = \{(.*?)\n\+\};', patch, re.S)
serials = re.findall(r'\{"([A-Z0-9]+)"\s*,\s*([A-Z0-9_]+)\}', m.group(1))
by_title = collections.defaultdict(list)
for serial, title in serials:
    by_title[title].append(serial)

# 2. config_change(): each "if (isTitleName(A) || ...) { statements }" group
menu = patch[patch.index('diff -ruw -N base/frontend/menu.c'):]
menu = menu[:menu.index('\ndiff -ruw', 10)]
body = menu[menu.index('+void config_change() {'):]
body = body[:body.index('\n+}\n') + 4]
body = '\n'.join(l[1:] for l in body.splitlines() if l.startswith('+'))

# what each statement means for us: (flag, comment)
KNOWN = {
    'spu_config.iUseInterpolation = 2': 'AB_HACK_SPU_GAUSSIAN',
    'spu_config.iUseInterpolation = 3': 'AB_HACK_SPU_CUBIC',
    'spu_config.iUseThread = 0': 'AB_HACK_SPU_NO_THREAD',
    'pl_rearmed_cbs.gpu_neon.allow_interlace = 0': 'AB_HACK_NO_INTERLACE',
    'Config.PsxType = 0': 'AB_HACK_NTSC',
}
DROPPED = ('spu_config.iTempo', 'Config.Gpu', 'gpu_peops.', 'Config.PsxAuto')

flags = collections.defaultdict(set)   # title -> flags
dropped = collections.OrderedDict()    # statement -> titles
for cond, stmts in re.findall(r'if\s*\(((?:[^{}])*?)\)\s*\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}', body, re.S):
    titles = re.findall(r'isTitleName\((\w+)\)', cond)
    if not titles:
        continue
    for line in stmts.splitlines():
        s = line.strip().rstrip(';')
        # a nested "if (isTitleName(...) || ...) {" inside a group (Toshinden inside the peops swap): its
        # condition lines are skipped, its statement is a peops flag handled below
        if not s or s.startswith('//') or s.startswith('if') or s.startswith('}') or 'isTitleName(' in s:
            continue
        if s in KNOWN:
            for t in titles:
                flags[t].add(KNOWN[s])
        elif any(d in s for d in DROPPED):
            dropped.setdefault(s, set()).update(titles)
        elif s:
            raise SystemExit('unknown statement in config_change: ' + s)

# nested "if (isTitleName(TOSHINDEN...)) { isToShinDen }" sits inside the Config.Gpu group: handled by the
# outer regex's nested-brace pattern; its statement is a dropped peops flag

out = []
out.append('/* Generated by tools/gen_sony_hacks.py from docs/reference/pcsx-ab-delta-2017.patch - do not edit.')
out.append(' * Sony\'s per-title configuration overrides (pcsx-ab\'s config_change() in frontend/menu.c, applied over')
out.append(' * pcsx.cfg at every start), keyed by the disc\'s serial (Sony keyed them on the ISO file name, which')
out.append(' * on the console *was* the serial). Kept: the overrides with an equivalent in upstream\'s core. Left out,')
out.append(' * for the record:')
for s, ts in dropped.items():
    out.append(' *   %s  (%d titles)' % (s, len(ts)))
out.append(' */')
out.append('')
out.append('#define AB_HACK_SPU_GAUSSIAN  (1 << 0)   /* spu_config.iUseInterpolation = 2 */')
out.append('#define AB_HACK_SPU_CUBIC     (1 << 1)   /* spu_config.iUseInterpolation = 3 */')
out.append('#define AB_HACK_SPU_NO_THREAD (1 << 2)   /* spu_config.iUseThread = 0 */')
out.append('#define AB_HACK_NO_INTERLACE  (1 << 3)   /* gpu_neon.allow_interlace = 0 */')
out.append('#define AB_HACK_NTSC          (1 << 4)   /* Config.PsxAuto = 0, Config.PsxType = 0 (NTSC) */')
out.append('')
out.append('static const struct ab_hack_entry {')
out.append('\tconst char *serial;')
out.append('\tunsigned int flags;')
out.append('\tconst char *title;')
out.append('} ab_hack_table[] = {')
n = 0
for serial, title in serials:
    f = flags.get(title)
    if not f:
        continue
    out.append('\t{ "%s", %s, "%s" },' % (serial, ' | '.join(sorted(f)), title))
    n += 1
out.append('};')
out.append('')
dst = os.path.join(root, 'frontend', 'ab', 'ab_hacks_table.h')
open(dst, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('%s: %d of %d serials carry an override; dropped statements: %s' % (os.path.relpath(dst, root), n, len(serials), ', '.join(dropped)))
